;; acceptable color-themes
;; (robin-hood gray30 kingsajz)


(defun color-theme-system-wide ()
  "Color theme by Dan Davison, created 2007-09-21."
  (interactive)
  
  ;; see C-h f 'color-theme-install'
  ;; The argument to color-theme-install is a list:
  ;; ([FUNCTION] FRAME-PARAMETERS VARIABLE-SETTINGS FACE-DEFINITIONS)
  ;; in which FRAME-PARAMETERS VARIABLE-SETTINGS FACE-DEFINITIONS are all alists.
  ;; I didn't know how to set values (i.e. CDRs) in the alist to be e.g. the string returned by (getenv "SOME_ENV_VARIABLE")
  ;; so have resorted to using sed to edit this elisp code from the shell script set-look...

  (color-theme-install
   '(color-theme-system-wide
     
     ;; an alist of frame parameters
     ((background-color . "#102e4e")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "LightGray")
      (foreground-color . "cyan")
      (mouse-color . "Grey"))
     
     ;; an alist of variable settings
     ((help-highlight-face . info-xref)
      (list-matching-lines-face . bold)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     
     ;; an alist of face definitions
     (default ((t (:stipple nil :background "darkslategrey" :foreground "#FFFFFF" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 116 :width normal :family "adobe-courier"))))
     
     ;; Things I might be interested in
     (font-lock-builtin-face ((t (:foreground "LightCoral"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#FF0000"))))
     (font-lock-comment-face ((t (:italic t :foreground "HotPink" :slant italic))))
     (font-lock-constant-face ((t (:foreground "gold"))))
     (font-lock-doc-face ((t (:foreground "BlanchedAlmond"))))
     (font-lock-doc-string-face ((t (:foreground "BlanchedAlmond"))))
     (font-lock-function-name-face ((t (:bold t :foreground "green" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "DeepSkyBlue1" :weight bold))))
     (font-lock-negation-char-face ((t (:foreground "red"))))
     (font-lock-preprocessor-face ((t (:foreground "gold"))))
     (font-lock-reference-face ((t (:foreground "LightCoral"))))
     (font-lock-string-face ((t (:foreground "burlywood"))))
     (font-lock-type-face ((t (:foreground "CadetBlue1"))))
     (font-lock-variable-name-face ((t (:foreground "SeaGreen2"))))
     (font-lock-warning-face ((t (:foreground "yellow"))))

     (fringe ((t (:background "#102e4e" :box (:line-width 0)))))

     (minibuffer-prompt ((t (:foreground "deep pink"))))
     (mode-line ((t (:background "#102e4e" :foreground "cyan" :box (:line-width 1 :style released-button)))))
     (mode-line-inactive ((t (:background "#F5DEB3" :foreground "#2F4F4F" :box (:line-width 1 :style released-button)))))
     (modeline-buffer-id ((t (:background "dark olive green" :foreground "beige"))))
     (modeline-mousable ((t (:background "dark olive green" :foreground "yellow green"))))
     (modeline-mousable-minor-mode ((t (:background "dark olive green" :foreground "wheat"))))
     (mouse ((t (:background "Grey"))))
     (region ((t (:background "dark cyan" :foreground "cyan"))))


     ;; Things that AFAIK I'm not interested in 
     (bbdb-company ((t (:foreground "pale green"))))
     (bbdb-field-name ((t (:foreground "medium sea green"))))
     (bbdb-field-value ((t (:foreground "dark sea green"))))
     (bbdb-name ((t (:bold t :foreground "pale green" :weight bold))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :foreground "beige" :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (button ((t (:bold t :weight bold))))
     (calendar-today-face ((t (:underline t))))
     (change-log-acknowledgement-face ((t (:foreground "LightBlue"))))
     (change-log-conditionals-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-date-face ((t (:foreground "LightSalmon"))))
     (change-log-email-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-file-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-function-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-list-face ((t (:foreground "Salmon"))))
     (change-log-name-face ((t (:foreground "Aquamarine"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "medium aquamarine"))))
     (cperl-array-face ((t (:bold t :foreground "tomato" :weight bold))))
     (cperl-hash-face ((t (:bold t :foreground "chocolate" :weight bold))))
     (cperl-nonoverridable-face ((t (:foreground "red"))))
     (cursor ((t (:background "LightGray"))))
     (custom-button-face ((t (:foreground "MediumSlateBlue" :underline t))))
     (custom-documentation-face ((t (:foreground "Grey"))))
     (custom-group-tag-face ((t (:foreground "MediumAquamarine"))))
     (custom-state-face ((t (:foreground "Coral"))))
     (custom-variable-tag-face ((t (:foreground "Aquamarine"))))
     (diary-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (diff-added-face ((t (nil))))
     (diff-changed-face ((t (nil))))
     (diff-context-face ((t (:foreground "grey70"))))
     (diff-file-header-face ((t (:bold t :weight bold))))
     (diff-function-face ((t (:foreground "grey70"))))
     (diff-header-face ((t (:foreground "light salmon"))))
     (diff-hunk-header-face ((t (:foreground "light salmon"))))
     (diff-index-face ((t (:bold t :weight bold))))
     (diff-nonexistent-face ((t (:bold t :weight bold))))
     (diff-removed-face ((t (nil))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-marked ((t (:foreground "light salmon"))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (erc-action-face ((t (nil))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "yellow" :weight bold))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "pale green"))))
     (erc-error-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-input-face ((t (:foreground "light blue"))))
     (erc-inverse-face ((t (:background "steel blue"))))
     (erc-keyword-face ((t (:bold t :foreground "orange" :weight bold))))
     (erc-notice-face ((t (:foreground "light salmon"))))
     (erc-pal-face ((t (:foreground "pale green"))))
     (erc-prompt-face ((t (:bold t :foreground "light blue" :weight bold))))
     (eshell-ls-archive-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "Grey"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "DimGray" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "MediumSlateBlue" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "Coral" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "black" :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
     (eshell-ls-special-face ((t (:bold t :foreground "Gold" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "White" :weight bold))))
     (eshell-ls-text-face ((t (:foreground "medium aquamarine"))))
     (eshell-ls-todo-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
     (eshell-prompt-face ((t (:foreground "powder blue"))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (fixed-pitch ((t (:family "courier"))))
     (gnus-cite-attribution-face ((t (:bold t :weight bold))))
     (gnus-cite-face-1 ((t (:foreground "dark khaki"))))
     (gnus-cite-face-2 ((t (:foreground "chocolate"))))
     (gnus-cite-face-3 ((t (:foreground "tomato"))))
     (gnus-cite-face-4 ((t (:foreground "yellow green"))))
     (gnus-cite-face-5 ((t (:foreground "dark khaki"))))
     (gnus-cite-face-6 ((t (:foreground "bisque"))))
     (gnus-cite-face-7 ((t (:foreground "peru"))))
     (gnus-cite-face-8 ((t (:foreground "light coral"))))
     (gnus-cite-face-9 ((t (:foreground "plum"))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-group-mail-1-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "tomato"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "tomato" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "dodger blue"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "dodger blue" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "green yellow"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "green yellow" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "dark orange"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "dark orange" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "tomato"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "tomato" :weight bold))))
     (gnus-group-news-4-empty-face ((t (:foreground "Aquamarine"))))
     (gnus-group-news-4-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (gnus-group-news-5-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-5-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-group-news-6-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-6-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "yellow green"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "yellow green" :weight bold))))
     (gnus-header-content-face ((t (:foreground "LightSkyBlue3"))))
     (gnus-header-from-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-header-name-face ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3" :slant italic :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-signature-face ((t (:foreground "salmon"))))
     (gnus-splash-face ((t (:foreground "ForestGreen"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "forest green" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "burlywood" :weight bold))))
     (gnus-summary-high-unread-face ((t (:italic t :bold t :foreground "cyan" :slant italic :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "chocolate" :slant italic))))
     (gnus-summary-low-read-face ((t (:foreground "light sea green"))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "chocolate" :slant italic))))
     (gnus-summary-low-unread-face ((t (:italic t :foreground "light sea green" :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "RoyalBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "khaki"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "sandy brown"))))
     (gnus-summary-normal-unread-face ((t (:foreground "aquamarine"))))
     (gnus-summary-selected-face ((t (:background "DarkSlateBlue"))))
     (header-line ((t (:box (:line-width 1 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (highlight ((t (:background "PaleGreen" :foreground "DarkGreen"))))
     (highline-face ((t (:background "SeaGreen"))))
     (holiday-face ((t (:background "DimGray"))))
     (hyper-apropos-documentation ((t (:foreground "LightSalmon"))))
     (hyper-apropos-hyperlink ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (info-header-xref ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (info-menu-5 ((t (:underline t))))
     (info-node ((t (:bold t :foreground "DodgerBlue1" :underline t :weight bold))))
     (info-xref ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (isearch ((t (:background "sea green"))))
     (isearch-lazy-highlight-face ((t (:background "paleturquoise4"))))
     (italic ((t (:italic t :slant italic))))
     (log-view-message-face ((t (:foreground "light salmon"))))
     (makefile-shell-face ((t (:background "linen"))))
     (menu ((t (:background "pink" :foreground "violet red"))))
     (message-cited-text-face ((t (:foreground "White"))))
     (message-header-cc-face ((t (:foreground "light cyan"))))
     (message-header-name-face ((t (:foreground "DodgerBlue1"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3" :slant italic :weight bold))))
     (message-header-other-face ((t (:foreground "LightSkyBlue3"))))
     (message-header-subject-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-xheader-face ((t (:foreground "DodgerBlue3"))))
     (message-separator-face ((t (:foreground "chocolate"))))
     (scroll-bar ((t (:background "grey75"))))
     (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (show-paren-match-face ((t (:bold t :background "Aquamarine" :foreground "steel blue" :weight bold))))
     (show-paren-mismatch-face ((t (:background "Red" :foreground "White"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (tool-bar ((t (:background "pink" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lemon chiffon" :foreground "violet red"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (w3m-anchor-face ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (w3m-arrived-anchor-face ((t (:bold t :foreground "DodgerBlue3" :weight bold))))
     (w3m-header-line-location-content-face ((t (:background "dark olive green" :foreground "wheat"))))
     (w3m-header-line-location-title-face ((t (:background "dark olive green" :foreground "beige"))))
     (widget-button-face ((t (:bold t :weight bold))))
     (widget-button-pressed-face ((t (:foreground "red"))))
     (widget-documentation-face ((t (:foreground "lime green"))))
     (widget-field-face ((t (:foreground "LightBlue"))))
     (widget-inactive-face ((t (:foreground "DimGray"))))
     (widget-single-line-field-face ((t (:foreground "LightBlue"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (zmacs-region ((t (:background "dark cyan" :foreground "cyan")))))))

(add-to-list 'color-themes 
 	     '(color-theme-system-wide "system-wide"))
